#!/usr/bin/env bash
#script that pings an IP address passed as an argument, pinging it 5 times
#if there is no argument, Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}i

if [ "$#" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
